# Generated by Django 5.2.7 on 2025-10-09 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name="To'liq ismi")),
                ('photo', models.ImageField(blank=True, null=True, upload_to='teachers/photos/', verbose_name='Foto')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name="Tug'ilgan sanasi")),
                ('death_date', models.DateField(blank=True, null=True, verbose_name='Vafot etgan sanasi')),
                ('birth_place', models.CharField(max_length=255, verbose_name="Tug'ilgan joyi")),
                ('profession', models.CharField(max_length=255, verbose_name="Kasbi / Cholg'u asbobi")),
                ('biography', models.TextField(verbose_name='Biografiyasi')),
                ('achievements', models.TextField(blank=True, null=True, verbose_name='Yutuqlari')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': "O'qituvchi",
                'verbose_name_plural': "O'qituvchilar",
                'ordering': ['full_name'],
            },
        ),
    ]
