# Generated by Django 5.2.7 on 2025-10-17 07:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Nom')),
                ('resource_type', models.CharField(choices=[('maqom', 'Maqom'), ('composition', 'Kompozitsiya')], max_length=20, verbose_name='Turi')),
                ('notes_file', models.FileField(blank=True, null=True, upload_to='meros/notes/', verbose_name='Nota fayli (PDF)')),
                ('lyrics', models.TextField(blank=True, null=True, verbose_name='Matni / Tavsifi')),
                ('youtube_link', models.URLField(blank=True, null=True, verbose_name='YouTube havolasi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meroslar', to='index.teacher', verbose_name='Muallif (agar bo‘lsa)')),
            ],
            options={
                'verbose_name': 'Meros',
                'verbose_name_plural': 'Meroslar',
                'ordering': ['-created_at'],
            },
        ),
    ]
