# Generated by Django 5.2.7 on 2025-11-21 11:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_meros'),
    ]

    operations = [
        migrations.CreateModel(
            name='Makom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Bolim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('mushkilot', 'Mushkilot'), ('nasr', 'Nasr')], max_length=50)),
                ('slug', models.SlugField(blank=True)),
                ('makom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bolimlar', to='index.makom')),
            ],
        ),
        migrations.CreateModel(
            name='Shoba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True)),
                ('bolim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shobalar', to='index.bolim')),
            ],
        ),
        migrations.CreateModel(
            name='Kuy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('notes', models.FileField(blank=True, null=True, upload_to='notes/')),
                ('youtube_link', models.URLField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True)),
                ('bolim', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='index.bolim')),
                ('shoba', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='index.shoba')),
            ],
        ),
    ]
