# Generated by Django 5.2.7 on 2025-11-25 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_makom_bolim_shoba_kuy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meros',
            name='resource_type',
            field=models.CharField(choices=[('asar', 'Xalq kuyi'), ('composition', 'Bastakorlik asari')], max_length=20, verbose_name='Turi'),
        ),
    ]
