# Generated by Django 5.2.7 on 2026-01-20 17:37

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_alter_meros_resource_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kuy',
            options={'ordering': ['name'], 'verbose_name': 'Kuy', 'verbose_name_plural': 'Kuylari'},
        ),
        migrations.AddField(
            model_name='kuy',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kuy',
            name='lyrics',
            field=models.TextField(blank=True, null=True, verbose_name='Matni / Tavsifi'),
        ),
        migrations.AlterField(
            model_name='kuy',
            name='bolim',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kuys', to='index.bolim'),
        ),
        migrations.AlterField(
            model_name='kuy',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Kuy nomi'),
        ),
        migrations.AlterField(
            model_name='kuy',
            name='notes',
            field=models.FileField(blank=True, null=True, upload_to='kuys/notes/', verbose_name='Nota (PDF)'),
        ),
        migrations.AlterField(
            model_name='kuy',
            name='shoba',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kuys', to='index.shoba'),
        ),
        migrations.AlterField(
            model_name='kuy',
            name='youtube_link',
            field=models.URLField(blank=True, null=True, verbose_name='YouTube havolasi'),
        ),
    ]
